---
lang: en
title: "torchcvnn: A PyTorch-based library to easily experiment with state-of-the-art Complex-Valued Neural Networks"
subtitle: "SONDRA Workshop"
author: Jeremy Fix, Quentin Gabot, X. Huy Nguyen, Joana Frontera-Pons, Chengfang Ren and Jean-Philippe Ovarlez
parallaxBackgroundImage: "./img/csbg.png"
duration: 15
theme: white
width: 1600
height: 1200
margin: 0.1
center: false
embedded: false
css: 
- custom.css
- https://www.w3schools.com/w3css/4/w3.css
hideAddressBar: true
rtl: false                 # Right to left or Left to Right
slideNumber: true  
rollingLinks: true         # Does not work
showNotes: false
fragments: true
transition: none
touch: true
keywords:
- torchcvnn
- ijcnn
---

